spring:
  application:
    name: "@project.artifactId@"
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
info:
  name: "@project.artifactId@"
  version: "@project.version@"
  description: "@project.description@"
  running-profile: ${spring.profiles.active}
  